
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost/barrage_site?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 15576123138
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2359536639@qq.com
    password: xwfchyeomxetebag
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
  redis:
    database: 0
    host: localhost
    port: 6379
server:
  port: 8080
  servlet:
    context-path:
#  ssl:
#    key-store: classpath:gornix.jks
#    key-store-type: JKS
#    key-password: 654321
#    key-alias: gornix

mail:
  from: ${spring.mail.username}



bilibiliApiUrl: https://api.bilibili.com/x/v2/reply

filePath: /usr/bilibiliComment

allowedOrigin: https://selltom.mynatapp.cc

ipRecordFilePath: /usr/barrage-site-visitor.txt
#ipRecordFilePath: D://barrage-site-visitor.txt

login:
  userKey: tomshidi/